// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace CapnpC.CSharp.Generator.Tests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CodeGeneratorFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "Coverage"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "CodeGenerator", "\tIn order to ensure that the generator backend produces valid output\n\tAs a contri" +
                "butor\n\tI want to get notified when there is any deviation from reference output", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CodeGenerator.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("CodeGenerator.feature.ndjson", 27);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="Comparing backend output with reference")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Comparing backend output with reference")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CodeGenerator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        public async global::System.Threading.Tasks.Task ComparingBackendOutputWithReference()
        {
            string[] tagsOfScenario = new string[] {
                    "Coverage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Comparing backend output with reference", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
 await testRunner.GivenAsync("I have a binary code generator request \"test.capnp.bin\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
 await testRunner.AndAsync("my reference output is \"test.cs\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
 await testRunner.WhenAsync("I invoke capnpc-csharp", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
 await testRunner.ThenAsync("the generated output must match the reference", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="Invalid binary code generator requests")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Invalid binary code generator requests")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CodeGenerator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("null.bin", "1", null, DisplayName="Invalid binary code generator requests(null.bin,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("test.cs", "2", null, DisplayName="Invalid binary code generator requests(test.cs,2)")]
        public async global::System.Threading.Tasks.Task InvalidBinaryCodeGeneratorRequests(string bin, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Coverage"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("bin", bin);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Invalid binary code generator requests", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
 await testRunner.GivenAsync(string.Format("I have a binary code generator request {0}", bin), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
 await testRunner.WhenAsync("I invoke capnpc-csharp", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.ThenAsync("the invocation must fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="Combining frontend and backend")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Combining frontend and backend")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CodeGenerator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        public async global::System.Threading.Tasks.Task CombiningFrontendAndBackend()
        {
            string[] tagsOfScenario = new string[] {
                    "Coverage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Combining frontend and backend", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 27
 await testRunner.GivenAsync("capnp.exe is installed on my system", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
 await testRunner.AndAsync("I have a schema \"UnitTest1.capnp\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
 await testRunner.WhenAsync("I try to generate code from that schema", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
 await testRunner.ThenAsync("code generation must succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="Missing frontend")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Missing frontend")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CodeGenerator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        public async global::System.Threading.Tasks.Task MissingFrontend()
        {
            string[] tagsOfScenario = new string[] {
                    "Coverage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Missing frontend", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
 await testRunner.GivenAsync("capnp.exe is not installed on my system", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
 await testRunner.AndAsync("I have a schema \"UnitTest1.capnp\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
 await testRunner.WhenAsync("I try to generate code from that schema", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
 await testRunner.ThenAsync("the invocation must fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="Schema without ID")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Schema without ID")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CodeGenerator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        public async global::System.Threading.Tasks.Task SchemaWithoutID()
        {
            string[] tagsOfScenario = new string[] {
                    "Coverage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Schema without ID", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
 await testRunner.GivenAsync("capnp.exe is installed on my system", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
 await testRunner.AndAsync("I have a schema \"Empty1.capnp\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
 await testRunner.WhenAsync("I try to generate code from that schema", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
 await testRunner.ThenAsync("the invocation must fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
 await testRunner.AndAsync("the reason must be bad input", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
 await testRunner.AndAsync("the error output must contain \"File does not declare an ID\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="Multiple errors")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Multiple errors")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CodeGenerator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        public async global::System.Threading.Tasks.Task MultipleErrors()
        {
            string[] tagsOfScenario = new string[] {
                    "Coverage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple errors", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
 await testRunner.GivenAsync("capnp.exe is installed on my system", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
 await testRunner.AndAsync("I have a schema \"invalid.capnp\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
 await testRunner.WhenAsync("I try to generate code from that schema", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
 await testRunner.ThenAsync("the invocation must fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
 await testRunner.AndAsync("the reason must be bad input", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
 await testRunner.AndAsync("the error output must contain multiple messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute(DisplayName="Valid generator output")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Valid generator output")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CodeGenerator")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Coverage")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("test.capnp.bin", "false", "false", "success", "7", null, DisplayName="Valid generator output(test.capnp.bin,false,false,success,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("test.capnp.bin", "true", "false", "errors", "8", null, DisplayName="Valid generator output(test.capnp.bin,true,false,errors,8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("test.capnp.bin", "false", "true", "warnings", "9", null, DisplayName="Valid generator output(test.capnp.bin,false,true,warnings,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("test.capnp.bin", "true", "true", "success", "10", null, DisplayName="Valid generator output(test.capnp.bin,true,true,success,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Issue19.capnp.bin", "false", "false", "success", "11", null, DisplayName="Valid generator output(Issue19.capnp.bin,false,false,success,11)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Issue21.capnp.bin", "false", "false", "success", "12", null, DisplayName="Valid generator output(Issue21.capnp.bin,false,false,success,12)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Issue22.capnp.bin", "false", "false", "success", "13", null, DisplayName="Valid generator output(Issue22.capnp.bin,false,false,success,13)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("IssueGenGeneric.capnp.bin", "false", "false", "success", "14", null, DisplayName="Valid generator output(IssueGenGeneric.capnp.bin,false,false,success,14)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("NullableDisable.capnp.bin", "true", "false", "success", "15", null, DisplayName="Valid generator output(NullableDisable.capnp.bin,true,false,success,15)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("NullableDisable.capnp.bin", "true", "true", "warnings", "16", null, DisplayName="Valid generator output(NullableDisable.capnp.bin,true,true,warnings,16)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("NullableEnable.capnp.bin", "false", "true", "success", "17", null, DisplayName="Valid generator output(NullableEnable.capnp.bin,false,true,success,17)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("NullableEnable.capnp.bin", "false", "false", "errors", "18", null, DisplayName="Valid generator output(NullableEnable.capnp.bin,false,false,errors,18)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("NullableDisable2.capnp.bin", "false", "false", "errors", "19", null, DisplayName="Valid generator output(NullableDisable2.capnp.bin,false,false,errors,19)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("NullableDisable2.capnp.bin", "false", "true", "success", "20", null, DisplayName="Valid generator output(NullableDisable2.capnp.bin,false,true,success,20)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("NullableEnable2.capnp.bin", "false", "false", "errors", "21", null, DisplayName="Valid generator output(NullableEnable2.capnp.bin,false,false,errors,21)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("NullableEnable2.capnp.bin", "false", "true", "success", "22", null, DisplayName="Valid generator output(NullableEnable2.capnp.bin,false,true,success,22)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("rpc-csharp.capnp.bin", "true", "true", "warnings", "23", null, DisplayName="Valid generator output(rpc-csharp.capnp.bin,true,true,warnings,23)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("schema-csharp.capnp.bin", "false", "false", "success", "24", null, DisplayName="Valid generator output(schema-csharp.capnp.bin,false,false,success,24)")]
        public async global::System.Threading.Tasks.Task ValidGeneratorOutput(string bin, string nullablegen, string nullablesupp, string outcome, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Coverage"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("bin", bin);
            argumentsOfScenario.Add("nullablegen", nullablegen);
            argumentsOfScenario.Add("nullablesupp", nullablesupp);
            argumentsOfScenario.Add("outcome", outcome);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Valid generator output", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
 await testRunner.GivenAsync(string.Format("I have a binary code generator request {0}", bin), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
 await testRunner.AndAsync(string.Format("I enable generation of nullable reference types according to {0}", nullablegen), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync(string.Format("I enable the compiler support of nullable reference types according to {0}", nullablesupp), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
 await testRunner.WhenAsync("I invoke capnpc-csharp", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
 await testRunner.ThenAsync(string.Format("the invocation must succeed and attempting to compile the generated code gives {0" +
                            "}", outcome), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
